"1 Sum of Array Elements"
n=int(input())
a=list(map(int,input().split()))
s=0
for i in a:
    s+=i
print(s)

"2 Maximum Value in Array"
n=int(input())
a=list(map(int,input().split()))
m=a[0]
for i in a:
    if i>m:
        m=i
print(m)

"3 Minimum Value in Array"
n=int(input())
a=list(map(int,input().split()))
m=a[0]
for i in a:
    if i<m:
        m=i
print(m)

"4 Reverse Array"
n=int(input())
a=list(map(int,input().split()))
for i in range(n-1,-1,-1):
    print(a[i],end=" ")
    
"5 Search Element in Array"
n=int(input())
a=list(map(int,input().split()))
x=int(input())
for i in a:
    if i==x:
        print("Element Found")
        break
else:
    print("Element Not Found")
    
"6 Count Even and Odd Numbers"
n=int(input())
a=list(map(int,input().split()))
e=0
o=0
for i in a:
    if i%2==0:
        e+=1
    else:
        o+=1
print("Even:",e)
print("Odd:",o)

"7 Copy Array Elements"
n=int(input())
a=list(map(int,input().split()))
b=[]
for i in a:
    b.append(i)
for i in b:
    print(i,end=" ")
    
"8 Sort Array in Ascending Order"
n=int(input())
a=list(map(int,input().split()))
for i in range(n):
    for j in range(i+1,n):
        if a[i]>a[j]:
            a[i],a[j]=a[j],a[i]
for i in a:
    print(i,end=" ")
    
"9 Second Largest Element"
n=int(input())
a=list(map(int,input().split()))
a.sort()
print(a[-2])

"10 Remove Duplicate Elements"
n=int(input())
a=list(map(int,input().split()))
b=[]
for i in a:
    if i not in b:
        b.append(i)
for i in b:
    print(i,end=" ")
    
    
    
'''1.Intelligent Numerical Processing Engine

A futuristic analytics organization continuously processes numerical datasets received from distributed computational systems.

During analysis, the processing engine must calculate the total sum of all elements present inside the array.

Design a Python program to find the sum of array elements.

Input Format
First line contains integer n
Second line contains n integers
Output Format

Print the sum of array elements.

Sample Input
5
1 2 3 4 5
Sample Output
15

2.Autonomous Maximum Value Detection System

An advanced AI computation laboratory continuously processes numerical arrays generated by distributed neural systems.

During validation, the processing engine must identify the largest value present inside the array.

Design a Python program using arrays.

Sample Input
5
10 25 7 99 45
Sample Output
99

3.Intelligent Minimum Value Analyzer

A futuristic numerical research organization processes massive datasets for optimization systems.

During analysis, the computation engine must determine the minimum value present in the array.

Design a Python program.

Sample Input
5
8 2 15 1 20
Sample Output
1

4.Secure Sequence Reversal Engine

A distributed cyber intelligence organization continuously processes encrypted numerical sequences.

During synchronization, the processing engine must reverse the order of array elements before transmission.

Design a Python program using arrays.

Sample Input
5
1 2 3 4 5
Sample Output
5 4 3 2 1

5.Intelligent Data Lookup Controller

A futuristic database organization continuously processes large numerical datasets for intelligent search operations.

During validation, the search engine must determine whether a target element exists in the array.

Design a Python program using arrays.

Input Format
First line contains integer n
Second line contains n integers
Third line contains target element
Sample Input
5
10 20 30 40 50
30
Sample Output
Element Found

6.Autonomous Numerical Classification Engine

A next-generation computational laboratory processes numerical sequences for intelligent classification systems.

During analysis, the processing engine must count how many even and odd numbers are present inside the array.

Design a Python program using arrays.

Sample Input
6
1 2 3 4 5 6
Sample Output
Even: 3
Odd: 3

7.Distributed Data Replication System

A futuristic cloud storage organization continuously transfers numerical datasets between distributed storage units.

During replication, the synchronization engine must copy all elements from one array into another array.

Design a Python program using arrays.

Sample Input
5
1 2 3 4 5
Sample Output
1 2 3 4 5
 
8.Intelligent Sorting Optimization Engine

A multinational analytics corporation processes massive numerical datasets for automated optimization systems.

During processing, the sorting engine must arrange all array elements in ascending order.

Design a Python program using arrays.

Sample Input
5
8 3 1 6 2
Sample Output
1 2 3 6 8

9.Advanced Numerical Ranking Controller

A futuristic AI research organization processes large numerical sequences for intelligent ranking systems.

During analysis, the computation engine must determine the second largest element present inside the array.

Design a Python program using arrays.

Sample Input
5
10 20 50 40 30
Sample Output
40

10.Intelligent Duplicate Elimination Engine

A distributed cyber analytics organization processes massive numerical datasets for secure synchronization systems.

During processing, the validation engine must remove duplicate elements from the array.

Design a Python program using arrays.

Sample Input
6
1 2 2 3 4 4
Sample Output
1 2 3 4
DEVELOPER MODE'''